# Generated by Django 4.1 on 2022-08-24 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='is_mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.is_mentor'),
        ),
    ]
