# Generated by Django 3.2.9 on 2022-08-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_crewpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
