# Generated by Django 3.2.9 on 2022-08-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_p_comment_p_recomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_recomment',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
