# Generated by Django 3.2.9 on 2022-08-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_alter_p_recomment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_recomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.p_comment'),
        ),
    ]
