# Generated by Django 4.1 on 2022-08-25 18:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0004_alter_p_recomment_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='P_Comment',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='P_ReComment',
            new_name='ReComment',
        ),
    ]
