# Generated by Django 3.2.9 on 2022-08-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_s_comment_p_comment_c_comment'),
        ('challenge', '0003_comcomment_secomment'),
        ('challenge', '0006_p_comment_s_comment_rename_comment_c_comment_and_more'),
    ]

    operations = [
    ]
