# Generated by Django 3.2.9 on 2022-08-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_merge_20220826_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='p_comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='s_comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='s_comment',
            name='user',
        ),
        migrations.AddField(
            model_name='senior',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='C_Comment',
        ),
        migrations.DeleteModel(
            name='P_Comment',
        ),
        migrations.DeleteModel(
            name='S_Comment',
        ),
    ]
